language: python
python:
  - "2.7"

sudo: false

cache:
  directories:
    - "~/.platformio"

addons:
  apt:
    packages:
      - libsdl2-dev

install:
  - pip install -U platformio

script:
  - ./misc/compile-test.sh
